services:
  - type: web
    name: ecommerce-fullstack-design
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@brand.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLIENT_URL
        value: https://client-one-roan-32.vercel.app
